global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:3000']
  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:3001']
  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment-service:3002']
  - job_name: 'station-service'
    static_configs:
      - targets: ['station-service:3003']
  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:3004']
